### ISSUE TITLE
Sound not play

### ISSUE THREAD

**Issue by palashsah** [apache/cordova-plugin-media#289]
In our app sound  not play in api level 28 but in API level 27 it is playing.in previous ticket your team told that this is template issue but  this is not a template issue.please update your plugin for API level version 28.

**Comment by tom908** [comment]
I am facing the same issue with this plugin.i am getting frustrated with this plugin.after that I used native player plugin to resolve the issue.you can try native media player.

**Comment by timbru31** [comment]
This is the template you need to fill in. Otherwise it's impossible for us to help you.

```
# Bug Report

## Problem

### What is expected to happen?



### What does actually happen?



## Information
<!-- Include all relevant information that might help understand and reproduce the problem -->



### Command or Code
<!-- What command or code is needed to reproduce the problem? -->



### Environment, Platform, Device
<!-- In what environment, on what platform or on which device are you experiencing the issue? -->



### Version information
<!-- 
What are relevant versions you are using?
For example:
Cordova: Cordova CLI, Cordova Platforms, Cordova Plugins 
Other Frameworks: Ionic Framework and CLI version
Operating System, Android Studio, Xcode etc.
-->



## Checklist
<!-- Please check the boxes by putting an x in the [ ] like so: [x] -->

- [ ] I searched for existing GitHub issues
- [ ] I updated all Cordova tooling to most recent version
- [ ] I included all the necessary information above

```

**Comment by tom908** [comment]
Palash don't trust them  they didn't solved your issue.In my case they every time closed my issue.

**Comment by erisu** [comment]
@palashsah please submit another issue ticket with a complete bug report form filled out.

Do not delete the form. It contains information we need so that we could provide you help. Make sure to provide as much of the information as possible and how to reproduce the issue, if you know how.

With out the information from that form, it is nearly impossible for us to reproduce an issue or provide any relative help because we lack information.

I personally have ran a test with:

| Cordova-Android  | Target SDK API  |  Compiled Target SDK API |  Minimum SDK API Version | Status |
|---|---|---|---| --- |
| 9 | 29 | 29 | 22 | ✅ |
| 9 | 28 | 28 | 22 | ✅ |
| 9 | 27 | 27 | 22 | ✅ |

They all worked for me.

**Comment by tom908** [comment]
Palash they told me many things,its work on every format this is wrong . please use any other plugin don't use this plugin.you faces several issues
